mode: dev
data_file_path: covr/data/rich-text-covr/cvprw-covr_train.csv
video_root: covr/data/rich-text-covr/videos
output_dir: features/gallery/vjepa_base/train
num_workers: 4
target_fps: 1
test: False
gdrive_folder_id: 1DNOwf0kN7UL2zD7a8OqJ1Yvz8vqtHcPb
gdrive_credentials: service-account.json