mode: prod
data_file_path: covr/data/val_test-covr-r/val-set_no-labels.json
video_root: covr/data/val_test-covr-r/videos/
splits:
  - webvid
  - ss2
output_dir: features/gallery/vjepa_gigantic/val
num_workers: 4
target_fps: 4
test: True