mode: dev
json_path: covr/data/covr-r/merged_webvid_ss2.json
video_root: covr/data/covr-r/videos
splits:
  - webvid
  - ss2
output_dir: features/queries/flan_large
pretrained_model: google/flan-t5-large
batch_size: 64
num_workers: 4