mode: dev
json_path: covr/data/covr-r/merged_webvid_ss2.json
video_root: covr/data/covr-r/videos
splits:
  - webvid
  - ss2
output_dir: video_embeddings/vjepa_base #TODO change output_dir to model name
batch_size: 1
num_workers: 4